apiVersion: policy/v1
kind: PodDistributionBudget
metadata:
  name: devopshub-pdb
  namespace: devopshub-development
spec:
  selector:
    matchLabels:
      app: devopshub-db
  minAvailable: 1
  # maxUnavailable: 1
