apiVersion: v1
kind: PodDistributionBudget
metadata:
  name: devopshub-pdb
  namespace: devopshub-development
spec:
  selector:
    matchLabels:
      app: devopshub-deployment
  # Define the budget using EXACTLY ONE of the two fields below:
  minAvailable: 2
  # maxUnavailable: 1
