---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopshub-db-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: devopshub-db
  template:
    metadata:
      name: devopshub-db
      labels:
        app: devopshub-db
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k3d-worker-1-0
      containers:
        - name: db
          image: mysql:8.4
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 300m
              memory: 600Mi
          volumeMounts:
            - name: devopshub-db-volume
              mountPath: /var/lib/mysql
#         readinessProbe:
#           exec:
#             command:
#               - mysqladmin
#               - ping
#               - -h
#               - localhost
#           initialDelaySeconds: 5
#           periodSeconds: 10
          env:
            - name: MYSQL_DATABASE
              value: devopshub
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: devopshub-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
      volumes:
        - name: devopshub-db-volume
          persistentVolumeClaim:
            claimName: devopshub-db-pvc
