apiVersion: v1
kind: Service
metadata:
  name: devopshub-svc
spec:
  type: ClusterIP
  selector:
    app: devopshub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: devopshub-db-svc
spec:
  type: ClusterIP
  selector:
    app: devopshub-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
