---
data_value: "pong"
operator_name: "Aakash"
emergency_snack: "Protein bar"
server_status: "barely running"
critical_number: 1
environment_name: "local"
container_excuse: "cant give"
dns_reaction: "alive and kicking"
developer_quote: "hehehehe"
yaml_count: "5"
incident_time: "production"
actual_cause: "Resolve"
final_verdict: "All good!"
