---
- name: Install packages
  hosts: all
  become: true
  gather_facts: true
  roles:
    - role: packages
      vars:
        shell_commands_list: >-
          {{
            [
              "echo 'Starting system check'",
              "uname -a",
              "uname -m"
            ] + (
              ["echo 'Install yum-config-manager if missing'", "sudo dnf install -y yum-utils"]
              if ansible_os_family == "RedHat" else []
            )
          }}
