name: QuickSpin Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      destroy_infra:
        description: Destroy the infra created
        type: boolean
        default: false
        required: false

env:
  AWS_REGION: us-east-1
  BUCKET_NAME: "quickspin-${{ github.repository_owner }}-backend"

permissions:
  id-token: write
  contents: write

jobs:
  linting:
    if: github.event.inputs.destroy_infra != 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Python Linting Tools
        run: |
          pip install flake8

      - name: Run Flake8 Check
        working-directory: python
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 yaml-to-json.py --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. Max complexity is set to 10
          flake8 yaml-to-json.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform Formatting (QuickSpin IaC)
        working-directory: IaC
        run: |
          terraform fmt -check

      - name: Install Ansible
        run: |
          sudo apt-get update -qq && sudo apt-get install -y ansible -qq > /dev/null 2>&1

      - name: Ansible Syntax Check
        working-directory: Ansible
        run: |
          ansible-playbook --syntax-check -i inventory_aws.aws_ec2.yml ansible-instruction.yml

  infra-deployment:
    needs: [linting]
    if: github.event.inputs.destroy_infra != 'true' && false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          pip install -r python/requirements.txt

      - name: Convert YAML -> TFVARS.JSON
        working-directory: python
        run: |
          python yaml-to-json.py | tee terraform.tfvars.json
          mv terraform.tfvars.json ../IaC/
          echo "tfvars=$(cat ../IaC/terraform.tfvars.json | jq -c .)" >> $GITHUB_OUTPUT

      - name: Connect to Cloud Provider
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Create remote backend bucket if not exists
        working-directory: IaC
        run: |
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket $BUCKET_NAME already exists, skipping creation."
          else
            echo "Bucket $BUCKET_NAME does not exist, creating..."
            aws s3 mb "s3://$BUCKET_NAME" --region "$AWS_REGION"
          fi

      - name: Terraform Infra Deployment
        working-directory: IaC
        run: |
          terraform init -backend-config="bucket=${{ env.BUCKET_NAME }}" -backend-config="key=terraform.tfstate"
          terraform plan -out=tfplan
          terraform apply --auto-approve tfplan

  configuration-management:
    needs: [infra-deployment]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Connect to Cloud Provider
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Install Ansible
        run: |
          sudo apt-get update -qq && sudo apt-get install -y ansible -qq > /dev/null 2>&1
          ansible-galaxy collection install amazon.aws community.aws > /dev/null 2>&1
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
          sudo dpkg -i session-manager-plugin.deb

      - name: Set Ansible config path
        run: |
          ls -l $GITHUB_WORKSPACE/Ansible
          echo "ANSIBLE_CONFIG=$GITHUB_WORKSPACE/Ansible/ansible.cfg" >> $GITHUB_ENV

      - name: Checking Ansible Installation
        run: |
          ansible --version
          ls -l /opt/pipx/venvs/ansible-core/bin/
          /opt/pipx/venvs/ansible-core/bin/python -m pip install boto3 botocore

      - name: Wait for SSM agent registration
        run: |
          echo "Waiting 60s for SSM agent..."
          sleep 60

      - name: Run Ansible Inventory and Playbook
        working-directory: Ansible
        # possible flags are --graph, --list and --host
        run: |
          ansible-inventory -i inventory_aws.aws_ec2.yml --list
          ansible-playbook -i inventory_aws.aws_ec2.yml ansible-instruction.yml

      - name: List out the current folders
        run: |
          echo "Repository structure" && ls

  destroy_infra:
    if: github.event.inputs.destroy_infra == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Connect to Cloud Provider
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Destroy Infra
        working-directory: IaC
        run: |
          terraform init -backend-config="bucket=${{ env.BUCKET_NAME }}" -backend-config="key=terraform.tfstate"
          terraform destroy --auto-approve
