name: QuickSpin Networking

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install PyYAML
        run: |
          pip install pyyaml

      - name: Convert YAML -> TFVARS.JSON
        working-directory: python
        run: |
          python yaml-to-json.py > terraform.tfvars.json
          cat terraform.tfvars.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Connect to Cloud Provider
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Validate connect to Cloud
        run: |
          aws sts get-caller-identity

      # - name: Terraform Init
      #   working-directory: IaC
      #   run: terraform init
